In [2]:
import torch
import torch.nn as nn
import math

class PositionalEncoding(nn.Module):
  def __init__(self, d_model, max_seq_len=5000):
    super().__init__()
    pe = torch.zeros(max_seq_len, d_model)
    positions = torch.arange(0,max_seq_len).unsqueeze(1).float()
    for pos in range(max_seq_len):
      for i in range(d_model // 2):
        angle = pos / (10000 ** (2 * i / d_model))
        pe[pos, 2*i]     = math.sin(angle)
        pe[pos, 2*i + 1] = math.cos(angle)
    self.register_buffer('pe', pe)
    # divisor_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
  def forward(self, x):
    seq_len = x.size(1)
    return x + self.pe[:seq_len, :]

In [3]:
# Hyperparameters
batch, seq_len, d_model = 2, 5, 16

# Embeddings ban gayi hain (random for testing)
embeddings = torch.randn(batch, seq_len, d_model)
print("Input shape:", embeddings.shape)

# PositionalEncoding object
pe_layer = PositionalEncoding(d_model=d_model)

# Forward pass
output = pe_layer(embeddings)
print("Output shape:", output.shape)

# Check — PE table ka pehla row dekho (position 0)
print("\nPE for position 0 (first 8 values):")
print(pe_layer.pe[0, :8])

# PE table ke alag positions compare karo
print("\nPE for position 1 (first 8 values):")
print(pe_layer.pe[1, :8])

print("\nPE for position 2 (first 8 values):")
print(pe_layer.pe[2, :8])

Input shape: torch.Size([2, 5, 16])
Output shape: torch.Size([2, 5, 16])

PE for position 0 (first 8 values):
tensor([0., 1., 0., 1., 0., 1., 0., 1.])

PE for position 1 (first 8 values):
tensor([0.8415, 0.5403, 0.3110, 0.9504, 0.0998, 0.9950, 0.0316, 0.9995])

PE for position 2 (first 8 values):
tensor([ 0.9093, -0.4161,  0.5911,  0.8066,  0.1987,  0.9801,  0.0632,  0.9980])
